language: ruby
services:
  - mongodb
before_install:
  - gem install bundler
gemfile:
  - Gemfile
  - Gemfile.rails32
  - Gemfile.rails40
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-19mode
matrix:
  exclude:
    - rvm: 2.2
      gemfile: Gemfile.rails32
notifications:
  email:
    recipients:
      - lest@brainspec.com
      - nashby@brainspec.com
      - dreamfall@brainspec.com
