language: ruby
sudo: false
services:
  - postgresql
  - mongodb
gemfile:
  - Gemfile
  - Gemfile.rails42
  - Gemfile.rails51
  - Gemfile.mongo_mapper
rvm:
  - 2.2.7
  - 2.3.3
  - 2.4.1
  - jruby-9.1.8.0
env:
  - DB=sqlite3
  - DB=postgresql
matrix:
  allow_failures:
    - rvm: jruby-9.1.8.0
branches:
  only:
    - master
notifications:
  email: false
