language: ruby
sudo: false
services:
  - mongodb
gemfile:
  - Gemfile
  - Gemfile.rails42
  - Gemfile.rails51
  - Gemfile.mongo_mapper
rvm:
  - 2.2.7
  - 2.3.3
  - 2.4.1
  - jruby-9.1.6.0
matrix:
  allow_failures:
    - gemfile: Gemfile.rails42
      rvm: ruby-head
    - gemfile: Gemfile.mongo_mapper
      rvm: ruby-head
branches:
  only:
    - master
notifications:
  email: false
