language: ruby
services:
  - mongodb
before_install:
  - gem install bundler
gemfile:
  - Gemfile
  - Gemfile.rails40
  - Gemfile.mongo_mapper
rvm:
  - 2.2
  - 2.3.0
  - jruby-9.0.5.0
notifications:
  email:
    recipients:
      - lest@brainspec.com
      - nashby@brainspec.com
      - dreamfall@brainspec.com
