language: ruby
sudo: false
services:
  - mongodb
gemfile:
  - Gemfile
  - Gemfile.rails42
  - Gemfile.mongo_mapper
rvm:
  - 2.2.6
  - 2.3.3
  - ruby-head
  - jruby-9.1.2.0
matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: Gemfile
      rvm: jruby-9.1.2.0
notifications:
  email: false
